version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: node_server
    ports:
      - "8080:8080"

  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:4200"
    depends_on:
      - server